#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const sharedEnvPath = path.join(repoRoot, 'env', '.env.shared');
const sharedEnvExamplePath = path.join(repoRoot, 'env', '.env.shared.example');

const OUTPUT_HEADER = '# Generated by scripts/env-sync.mjs from env/.env.shared\n';

const targets = [
  {
    name: 'tracking-api',
    outputPath: path.join(repoRoot, 'apps', 'tracking-api', '.env'),
    keys: [
      'PORT',
      'DATABASE_URL',
      'TEST_DATABASE_URL',
      'REDIS_URL',
      'ROUTER_QUEUE_NAME',
      'ROUTER_WORKER_NAME',
      'ROUTER_WORKER_CONCURRENCY',
      'REDIS_HOST',
      'REDIS_PORT',
      'REDIS_DB',
      'REDIS_USERNAME',
      'REDIS_PASSWORD',
      'NODE_ENV',
      'METRICS_ENABLED',
      'TRACKING_API_AUTH_MODE',
      'TRACKING_API_SECRET',
      'TRACKING_SIGNATURE_SKEW_SECONDS',
      'TRACKING_RATE_LIMIT_ENABLED',
      'TRACKING_RATE_LIMIT_WINDOW_MS',
      'TRACKING_RATE_LIMIT_MAX_REQUESTS',
      'TRACKING_CORS_ALLOW_ORIGINS'
    ],
    required: ['PORT', 'DATABASE_URL', 'TRACKING_API_AUTH_MODE']
  },
  {
    name: 'router-worker',
    outputPath: path.join(repoRoot, 'apps', 'router-worker', '.env'),
    keys: [
      'REDIS_URL',
      'DATABASE_URL',
      'ROUTER_QUEUE_NAME',
      'ROUTER_WORKER_NAME',
      'ROUTER_WORKER_CONCURRENCY',
      'META_CONVERSIONS_ENDPOINT_URL',
      'META_PIXEL_ID',
      'META_ACCESS_TOKEN',
      'META_TEST_EVENT_CODE',
      'GOOGLE_CONVERSIONS_ENDPOINT_URL',
      'GOOGLE_CONVERSIONS_API_KEY',
      'TIKTOK_EVENTS_ENDPOINT_URL',
      'TIKTOK_ACCESS_TOKEN'
    ],
    required: ['REDIS_URL', 'ROUTER_QUEUE_NAME', 'ROUTER_WORKER_NAME', 'ROUTER_WORKER_CONCURRENCY']
  },
  {
    name: 'deploy-app',
    outputPath: path.join(repoRoot, 'deploy', 'app', '.env'),
    keys: [
      'TRACKING_CONSOLE_IMAGE',
      'TRACKING_API_IMAGE',
      'ROUTER_WORKER_IMAGE',
      'TRACKING_CONSOLE_PORT',
      'TRACKING_API_PORT',
      'DATABASE_URL',
      'ADMIN_API_TOKEN',
      'REDIS_URL',
      'ROUTER_QUEUE_NAME',
      'ROUTER_WORKER_NAME',
      'ROUTER_WORKER_CONCURRENCY',
      'TRACKING_API_AUTH_MODE',
      'TRACKING_API_SECRET',
      'TRACKING_SIGNATURE_SKEW_SECONDS',
      'TRACKING_RATE_LIMIT_ENABLED',
      'TRACKING_RATE_LIMIT_WINDOW_MS',
      'TRACKING_RATE_LIMIT_MAX_REQUESTS',
      'TRACKING_CORS_ALLOW_ORIGINS',
      'METRICS_ENABLED',
      'META_CONVERSIONS_ENDPOINT_URL',
      'META_PIXEL_ID',
      'META_ACCESS_TOKEN',
      'META_TEST_EVENT_CODE',
      'GOOGLE_CONVERSIONS_ENDPOINT_URL',
      'GOOGLE_CONVERSIONS_API_KEY',
      'TIKTOK_EVENTS_ENDPOINT_URL',
      'TIKTOK_ACCESS_TOKEN'
    ],
    required: ['TRACKING_API_IMAGE', 'ROUTER_WORKER_IMAGE', 'DATABASE_URL', 'REDIS_URL']
  },
  {
    name: 'deploy-infra',
    outputPath: path.join(repoRoot, 'deploy', 'infra', '.env'),
    keys: ['REDIS_PORT'],
    required: ['REDIS_PORT']
  }
];

function stripInlineComment(value) {
  const index = value.search(/\s+#/);
  if (index === -1) {
    return value;
  }
  return value.slice(0, index).trimEnd();
}

function parseEnv(content) {
  const values = new Map();
  const lines = content.split(/\r?\n/);

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const normalizedLine = line.startsWith('export ') ? line.slice(7).trimStart() : line;
    const eqIndex = normalizedLine.indexOf('=');
    if (eqIndex <= 0) {
      continue;
    }

    const key = normalizedLine.slice(0, eqIndex).trim();
    let value = normalizedLine.slice(eqIndex + 1);

    if (!/^[_A-Za-z][_A-Za-z0-9]*$/.test(key)) {
      continue;
    }

    const trimmedValue = value.trim();
    if (
      (trimmedValue.startsWith('"') && trimmedValue.endsWith('"')) ||
      (trimmedValue.startsWith("'") && trimmedValue.endsWith("'"))
    ) {
      value = trimmedValue;
    } else {
      value = stripInlineComment(value).trim();
    }

    values.set(key, value);
  }

  return values;
}

function loadSharedValues() {
  if (!fs.existsSync(sharedEnvPath)) {
    const hint = fs.existsSync(sharedEnvExamplePath)
      ? 'Copy env/.env.shared.example to env/.env.shared and fill values first.'
      : 'Create env/.env.shared first.';
    throw new Error(`Missing ${sharedEnvPath}. ${hint}`);
  }

  const raw = fs.readFileSync(sharedEnvPath, 'utf8');
  return parseEnv(raw);
}

function isMissingValue(value) {
  return value === undefined || value === null || String(value).trim() === '';
}

function findMissingRequired(sharedValues) {
  const errors = [];

  for (const target of targets) {
    const missing = target.required.filter((key) => isMissingValue(sharedValues.get(key)));
    if (missing.length > 0) {
      errors.push({ target: target.name, missing });
    }
  }

  return errors;
}

function writeTargetEnvFiles(sharedValues) {
  for (const target of targets) {
    const bodyLines = target.keys.map((key) => `${key}=${sharedValues.get(key) ?? ''}`);
    const output = `${OUTPUT_HEADER}${bodyLines.join('\n')}\n`;
    fs.writeFileSync(target.outputPath, output, 'utf8');
    console.log(`Updated ${path.relative(repoRoot, target.outputPath)}`);
  }
}

function check(sharedValues) {
  const errors = findMissingRequired(sharedValues);
  if (errors.length === 0) {
    console.log('All required env vars are present in env/.env.shared');
    return;
  }

  console.error('Missing required env vars in env/.env.shared:');
  for (const error of errors) {
    console.error(`- ${error.target}: ${error.missing.join(', ')}`);
  }
  process.exitCode = 1;
}

function sync(sharedValues) {
  const errors = findMissingRequired(sharedValues);
  if (errors.length > 0) {
    console.error('Cannot sync because required vars are missing in env/.env.shared:');
    for (const error of errors) {
      console.error(`- ${error.target}: ${error.missing.join(', ')}`);
    }
    process.exit(1);
  }

  writeTargetEnvFiles(sharedValues);
}

function main() {
  const mode = process.argv[2] || 'sync';
  if (!['sync', 'check'].includes(mode)) {
    console.error('Usage: node scripts/env-sync.mjs [sync|check]');
    process.exit(1);
  }

  const sharedValues = loadSharedValues();

  if (mode === 'check') {
    check(sharedValues);
    return;
  }

  sync(sharedValues);
}

main();
